Feature/72-support-aggregate-and-analytics-functions
exasol/sql-statement-builder pull request #122
Opened 2021-09-23 14:41 UTC by kaklakariada

Closes #72

2021-09-29 09:21 UTC, kaklakariada commented on src/test/java/com/exasol/sql/dql/select/rendering/TestSelectRendering.java
> +                                        .exclude(WindowFrameExclusionType.CURRENT_ROW)),
Proposed API for creating an OVER clause.

2021-09-29 09:52 UTC, jakobbraun commented on doc/changes/changes_4.5.0.md
> +We also addes support for the keywords `DISTINCT` and `ANY` as well as the [over_clause](https://docs.exasol.com/sql_references/functions/analyticfunctions.htm?Highlight=over_clause) for analytic fun
```suggestion
We also added support for the keywords `DISTINCT` and `ANY` as well as the [over_clause](https://docs.exasol.com/sql_references/functions/analyticfunctions.htm?Highlight=over_clause) for analytic functions.
```

2021-09-29 09:52 UTC, jakobbraun commented on doc/user_guide/statements/select.md
> +Function function = AnalyticFunction.of(ExasolAnalyticFunction.ANY, Keyword.DISTINCT,
Maybe we could do something like a builder here too? It's lots of parameters and I did not get immediately what the mean.

2021-09-30 06:06 UTC, jakobbraun requested changes

2021-09-30 06:06 UTC, jakobbraun commented on src/main/java/com/exasol/sql/expression/rendering/OverClauseRenderer.java
> +
```suggestion
```

2021-09-30 06:06 UTC, jakobbraun commented on src/main/java/com/exasol/sql/expression/rendering/OverClauseRenderer.java
> +                throw new IllegalStateException(messageBuilder("E-ESB-2").message("Expression is missing.")
can you add more information here? I would not know for what the expression is missing.

2021-09-30 07:05 UTC, kaklakariada commented on src/main/java/com/exasol/sql/expression/function/exasol/ExasolAggregateFunction.java
>  public enum ExasolAggregateFunction implements FunctionName {
It works with the normal `ExasolFunction`. The `AnalyticFunction` class requires `ExasolAnalyticAggregateFunctions`.

2021-09-30 07:18 UTC, jakobbraun commented on src/main/java/com/exasol/sql/expression/function/exasol/ExasolAggregateFunction.java
>  public enum ExasolAggregateFunction implements FunctionName {
:+1:

2021-09-30 07:19 UTC, jakobbraun approved these changes

2021-09-30 08:02 UTC, merged